---
title: "Untitled"
author: "Narjes Mathlouthi"
date: '2022-04-18'
output:
  pdf_document: default
  html_document: default
editor_options:
  markdown:
    wrap: 72
---

Narjes Mathlouthi (510) 698-2829 \|
[nmathlouthi\@ucsb.edu](mailto:nmathlouthi@ucsb.edu){.email} \| GitHub
\| LinkedIn \| Santa Barbara, CA EDUCATION Master of Environmental
Science and Management (Expected June 2023) Water Resources Management &
Energy and Climate Specializations Bren School of Environmental Science
& Management -- University of California, Santa Barbara (UCSB) Bachelor
of Science Environmental Economics & Policy, 3.8 GPA (December 2016)
University of California Berkeley (UC Berkeley), Berkeley, CA
Leadership/Involvement: Berkeley Environmental Economics & Policy Group
EXPERIENCE Women4Good, San Francisco CA Marketing Analyst (6/21--8/21) ●
Increased IGNITE National's Instagram growth from 2.5% daily engagement
to 5% ● Conducted a historical analysis and provided recommendations to
IGNITE's team ● Co-designed and launched a campaign Museum of African
Diaspora (MoAD), San Francisco, CA Data Defender (07/20 -- 06/21) ●
Maintained museum database; cleaned and updated inaccurate data weekly ●
Protected donors/user's information and collected and designed surveys
Global Fund for Women, San Francisco, CA (08/18--05/21) Grants Officer
(11/20 -- 15/21) ● Manage 350+ grants pre-post award ● Review
procurement and safeguarding policies ● Oversee contracts, payment
processing & assure contract and grant compliance ● Communicate with
donors, program & fundraising team to achieve grantmaking strategies ●
Refine, improve and implement tools, reports and procedures to optimize
grantmaking planning processes ● Develop, launch and manage in-depth
dashboards and reports for all team functions on both management and
individual levels ● Maintain data quality by identifying and deleting
duplicate records, cleansing and updating inaccurate data ● Supervise,
and train 4 outside consultants, monitor project administration,
invoices, reporting Grants Coordinator (08/18 -- 11/20) ● Assist grants
manager with grantmaking processes, contract review & payments ●
Coordinate grant agreements, & amendments ● Support grantee partners &
communicate with advisors to meet internal teams' requests ● Provide
Salesforce user support to partners, consultants and employees ● Update
website and informational database with necessary information or
important announcements ● Translate material in French & English
ADDITIONAL EXPERIENCE Teaching Assistant -- Department of Economics,
UCSB, Santa Barbara, Goleta, CA (10/21--Present) ● Teach Introduction to
Economics' sections twice per week for a total of 56 students ● Prepare,
update and organize section material ● Grade students' homework and
provide feedback SKILLS & CERTIFICATIONS Data Analysis & Programming:
Python, R, JavaScript, C, HTML, CSS, SQL, APEX, Salesforce CRM
Communication Tools: WordPress, Microsoft Word and PowerPoint, Zoom,
Box, Google Suite Languages: French, Arabic Certifications: Python Data
Structure, RAD Women Intro to Coding PART I & II
